### ISSUE TITLE
Readme Typo?

### ISSUE THREAD

**Issue by pwall2222** [ApparyllisOrg/simply_sdk#4]
From the blogpost of [the 1.8 release](https://apparyllis.com/simply-plural-1-8-important-notice/), it was announced that Apparyllis would move out of Firebase, but in the README it says:

> Storing Authentication received from the Firebase SDK

Is it an out-of-date README?

**Comment by Cellaryllis** [comment]
Never got notified of this issue on github, yes that is an out of date readme. pubspec.yaml shows all dependencies.
